siteTitle = 'Anton Pivniuk'
siteDescr = 'UI/UX Engineer'

siteBandcampUrl = ''
siteSoundcloudUrl = ''
siteFacebookUrl = ''
siteDiscogsUrl = ''
siteTwitterUrl = ''
siteGoogleplusUrl = ''
siteGithubUrl = ''

poweredUrl = 'http://ihororlovskyi.com'
poweredTitle = 'Ihor Orlovskyi'

linkPrefix = ''
